// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThietBi_UNETI04_DHTI17A2HN.Data;

#nullable disable

namespace QuanLyThietBi_UNETI04_DHTI17A2HN_UNETI04_DHTI17A2HN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.ChiTietSuaChua", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KetQuaChanDoan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaKyThuatVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLinhKien")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaKyThuatVien");

                    b.HasIndex("MaLinhKien");

                    b.HasIndex("MaPhieu");

                    b.ToTable("ChiTietSuaChua");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiKhachHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.LinhKien", b =>
                {
                    b.Property<int>("MaLinhKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLinhKien"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LoaiLinhKien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenLinhKien")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLinhKien");

                    b.ToTable("LinhKien");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.LoaiThietBi", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("HangSanXuat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThoiHanBaoHanhMacDinh")
                        .HasColumnType("int");

                    b.HasKey("MaLoai");

                    b.HasIndex("TenLoai")
                        .IsUnique();

                    b.ToTable("LoaiThietBi");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.PhieuSuaChua", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<DateTime?>("HanDuKien")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<string>("MucDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungLoi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaThietBi");

                    b.ToTable("PhieuSuaChua");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.ThietBi", b =>
                {
                    b.Property<int>("MaThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietBi"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HanBaoHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayMua")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThietBi");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaLoai");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("ThietBi");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.ChiTietSuaChua", b =>
                {
                    b.HasOne("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.TaiKhoan", "KyThuatVien")
                        .WithMany("ChiTietSuaChuas")
                        .HasForeignKey("MaKyThuatVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.LinhKien", "LinhKien")
                        .WithMany("ChiTietSuaChuas")
                        .HasForeignKey("MaLinhKien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.PhieuSuaChua", "PhieuSuaChua")
                        .WithMany("ChiTietSuaChuas")
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyThuatVien");

                    b.Navigation("LinhKien");

                    b.Navigation("PhieuSuaChua");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.KhachHang", b =>
                {
                    b.HasOne("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.KhachHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.PhieuSuaChua", b =>
                {
                    b.HasOne("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("PhieuSuaChuas")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.ThietBi", "ThietBi")
                        .WithMany("PhieuSuaChuas")
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.ThietBi", b =>
                {
                    b.HasOne("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("ThietBis")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.LoaiThietBi", "LoaiThietBi")
                        .WithMany("ThietBis")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("LoaiThietBi");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("PhieuSuaChuas");

                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.LinhKien", b =>
                {
                    b.Navigation("ChiTietSuaChuas");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.LoaiThietBi", b =>
                {
                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.PhieuSuaChua", b =>
                {
                    b.Navigation("ChiTietSuaChuas");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("ChiTietSuaChuas");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyThietBi_UNETI04_DHTI17A2HN.Models.Entities.ThietBi", b =>
                {
                    b.Navigation("PhieuSuaChuas");
                });
#pragma warning restore 612, 618
        }
    }
}
